# Generated by Django 4.1.6 on 2024-02-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_enrollment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='JoiningDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
