# Generated by Django 4.1.6 on 2024-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_subplan_subplanfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='highlight_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
